//PROFILE

POST http://localhost:8080/profile/register
Content-Type: application/json

{
  "firstName": "Seppi",
  "lastName": "Stieg",
  "email": "stiegjosef@gmail.com",
  "phoneNumber": "0660 1150403",
  "password": "TestPasswort"
}

###

POST http://localhost:8080/profile/login
Content-Type: application/json

{
  "email": "test3.test@gmail.com",
  "password": "TestTest3!"
}

###

GET http://localhost:8080/profile/list
Content-Type: */*


############

//GENERAL INFO

POST http://localhost:8080/info/add
Content-Type: application/json

{
  "profile": {
    "id": 1,
    "firstName": "Jakob",
    "lastName": "Schlager",
    "email": "jak.schlag@gmail.com",
    "phoneNumber": "7589748392"
  },
  "zipCode": "7477",
  "city": "Houston",
  "gender": "Divers",
  "address": "Houston Street 187"
}

###

POST http://localhost:8080/info/update
Content-Type: application/json

{
  "profile": {
    "id": 1,
    "firstName": "Jakob",
    "lastName": "Schlager",
    "email": "jak.schlag@gmail.com",
    "phoneNumber": "7589748392"
  },
  "zipCode": "7477",
  "city": "husten",
  "gender": "Divers",
  "address": "Houston Street 187"
}